// The twenty-two case studies, as one array.
//
// ONE FILE PER STUDY, the convention src/content/insights and
// src/content/services already use. The order is the order the live
// /case-studies index lists them in, which is the agency's own curation of its
// work, so it is preserved rather than re-sorted.
//
// Generated by scripts/migrate-case-studies/convert.py.

import type { Study } from "@/content/case-studies";

import { study as sHealthyFarm } from "@/content/case-studies/healthy-farm";
import { study as sShassGifts } from "@/content/case-studies/shass-gifts";
import { study as sAccGulf } from "@/content/case-studies/acc-gulf";
import { study as sHelpsters } from "@/content/case-studies/helpsters";
import { study as sWafesRefrigerationIndustry } from "@/content/case-studies/wafes-refrigeration-industry";
import { study as sNeoData } from "@/content/case-studies/neo-data";
import { study as sAriizInternational } from "@/content/case-studies/ariiz-international";
import { study as sOnyxContracting } from "@/content/case-studies/onyx-contracting";
import { study as sDgrAviation } from "@/content/case-studies/dgr-aviation";
import { study as sMasterkraft } from "@/content/case-studies/masterkraft";
import { study as sUltracare } from "@/content/case-studies/ultracare";
import { study as sPkfuae } from "@/content/case-studies/pkfuae";
import { study as sAutobahn } from "@/content/case-studies/autobahn";
import { study as sAllday } from "@/content/case-studies/allday";
import { study as sDatagram } from "@/content/case-studies/datagram";
import { study as sSupercad } from "@/content/case-studies/supercad";
import { study as sTopshelf } from "@/content/case-studies/topshelf";
import { study as sArbritsafety } from "@/content/case-studies/arbritsafety";
import { study as sSaifeecomputers } from "@/content/case-studies/saifeecomputers";
import { study as sRoyalcaviar } from "@/content/case-studies/royalcaviar";
import { study as sLotus } from "@/content/case-studies/lotus";
import { study as sVenesta } from "@/content/case-studies/venesta";

export const studies: Study[] = [
  sHealthyFarm,
  sShassGifts,
  sAccGulf,
  sHelpsters,
  sWafesRefrigerationIndustry,
  sNeoData,
  sAriizInternational,
  sOnyxContracting,
  sDgrAviation,
  sMasterkraft,
  sUltracare,
  sPkfuae,
  sAutobahn,
  sAllday,
  sDatagram,
  sSupercad,
  sTopshelf,
  sArbritsafety,
  sSaifeecomputers,
  sRoyalcaviar,
  sLotus,
  sVenesta,
];
