// The thirty-five portfolio projects, as one array.
//
// ONE FILE PER PROJECT, the convention src/content/case-studies,
// src/content/insights and src/content/services already use.
//
// THE ORDER IS THE LIVE INDEX'S OWN. Its three tabs are walked in the order
// the site lists them -- Digital Marketing, Video Production, Web Design --
// and a project takes the position of its first appearance. Nine projects are
// filed under two tabs and appear once here, with one page and one URL.
//
// Generated by scripts/migrate-portfolio/convert.py.

import type { Project } from "@/content/portfolio";

import { project as pAllday } from "@/content/portfolio/allday";
import { project as pAutobahnCarRental } from "@/content/portfolio/autobahn-car-rental";
import { project as pDatagram } from "@/content/portfolio/datagram";
import { project as pHealthyFarmEatery } from "@/content/portfolio/healthy-farm-eatery";
import { project as pLotusDentalClinic } from "@/content/portfolio/lotus-dental-clinic";
import { project as pPkf } from "@/content/portfolio/pkf";
import { project as pRoyalCaviar } from "@/content/portfolio/royal-caviar";
import { project as pUltracare } from "@/content/portfolio/ultracare";
import { project as pVenesta } from "@/content/portfolio/venesta";
import { project as pEnhShowReel } from "@/content/portfolio/enh-show-reel";
import { project as pBindasmalGroup } from "@/content/portfolio/bindasmal-group";
import { project as pFabcon } from "@/content/portfolio/fabcon";
import { project as pNewEast } from "@/content/portfolio/new-east";
import { project as pOriental } from "@/content/portfolio/oriental";
import { project as pCConcepts } from "@/content/portfolio/c-concepts";
import { project as pScionInternational } from "@/content/portfolio/scion-international";
import { project as pSigntrade } from "@/content/portfolio/signtrade";
import { project as pTexol } from "@/content/portfolio/texol";
import { project as pUisInspection } from "@/content/portfolio/uis-inspection";
import { project as pArbritSafety } from "@/content/portfolio/arbrit-safety";
import { project as pAxclLubes } from "@/content/portfolio/axcl-lubes";
import { project as pEcosysIntegratedSolutions } from "@/content/portfolio/ecosys-integrated-solutions";
import { project as pEmitacHealthcare } from "@/content/portfolio/emitac-healthcare";
import { project as pFapinex } from "@/content/portfolio/fapinex";
import { project as pGlassWorld } from "@/content/portfolio/glass-world";
import { project as pKaishan } from "@/content/portfolio/kaishan";
import { project as pKbh } from "@/content/portfolio/kbh";
import { project as pMasterkraft } from "@/content/portfolio/masterkraft";
import { project as pMatrixfinishes } from "@/content/portfolio/matrixfinishes";
import { project as pMenopauseLivia } from "@/content/portfolio/menopause-livia";
import { project as pNalsoft } from "@/content/portfolio/nalsoft";
import { project as pQuadbikeindubai } from "@/content/portfolio/quadbikeindubai";
import { project as pSaifeeComputers } from "@/content/portfolio/saifee-computers";
import { project as pSupercadTrading } from "@/content/portfolio/supercad-trading";
import { project as pTopShelfTechnicalServices } from "@/content/portfolio/top-shelf-technical-services";

export const projects: Project[] = [
  pAllday,
  pAutobahnCarRental,
  pDatagram,
  pHealthyFarmEatery,
  pLotusDentalClinic,
  pPkf,
  pRoyalCaviar,
  pUltracare,
  pVenesta,
  pEnhShowReel,
  pBindasmalGroup,
  pFabcon,
  pNewEast,
  pOriental,
  pCConcepts,
  pScionInternational,
  pSigntrade,
  pTexol,
  pUisInspection,
  pArbritSafety,
  pAxclLubes,
  pEcosysIntegratedSolutions,
  pEmitacHealthcare,
  pFapinex,
  pGlassWorld,
  pKaishan,
  pKbh,
  pMasterkraft,
  pMatrixfinishes,
  pMenopauseLivia,
  pNalsoft,
  pQuadbikeindubai,
  pSaifeeComputers,
  pSupercadTrading,
  pTopShelfTechnicalServices,
];
